spring.application.name=ai-review-service
server.port=8085

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=codeguardian
spring.rabbitmq.password=codeguardian123

ai.provider=openai
ai.api-url=https://api.openai.com/v1
ai.api-key=YOUR_API_KEY
ai.model=YOUR_MODEL
