spring.application.name=github-service
server.port=8084

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=codeguardian
spring.rabbitmq.password=codeguardian123

github.api-url=https://api.github.com
github.token=dummy_token
