spring.application.name=scan-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/codeguardian_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rcs@#192019

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=codeguardian
spring.rabbitmq.password=codeguardian123
